client_data = ->
  prepay = parseInt($('select#prepay').val())
  $recipient_name = $('input#recipient_name')
  $recipient_name_div = $recipient_name.closest('div.form-group')
  $recipient_phone = $('input#recipient_phone')
  $recipient_phone_div = $recipient_phone.closest('div.form-group')
  if prepay == 100
    $recipient_name.attr 'required', 'required'
    $recipient_phone.attr 'required', 'required'
    $recipient_name_div.addClass 'required'
    $recipient_phone_div.addClass 'required'
  else
    $recipient_name.removeAttr 'required'
    $recipient_phone.removeAttr 'required'
    $recipient_name_div.removeClass 'required'
    $recipient_phone_div.removeClass 'required'
  return

$(document).ready ->
  client_data()
  $('select#prepay').on 'change', ->
    client_data()
    return
  return

# ---
# generated by js2coffee 2.2.0